version: '3.8'

services:
  # Backend контейнер
  backend:
    container_name: backend_l_r
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www 
      - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
    command: php-fpm
    depends_on:
      - db

  # Nginx контейнер для вебсервера
  nginx:
    container_name: nginx_l_r
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  # MySQL контейнер
  db:
    container_name: db_l_r
    image: mysql:5.7
    platform: linux/amd64
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'appuser'
      MYSQL_PASSWORD: 'appuser'
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]

  # Phpmyadmin контейнер
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin_l_r
    restart: unless-stopped
    ports:
      - "8087:80"
    environment:
      PMA_HOST: db_l_r
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  # Для сборки js
  node:
    container_name: node_l_r
    build:
        context: .
        dockerfile: ./docker/nodejs/Dockerfile
    tty: true
    ports:
        - "5173:5173"
    working_dir: /var/www
    volumes:
        - .:/var/www

# Тома
volumes:
  # Чтобы данные БД не пропадали после выключения создаем именованный том
  dbdata:
    driver: local
